[[language]]
name = "hcl"
scope = "source.tf"
roots = ["main.tf", ".terraform.d"]
file-types = ["hcl", "tf"]
auto-format = true
language-servers = [ "terraform-lsp" ]
formatter = { command = "tofu" , args = ["fmt", "-"] }

[[language]]
name = "templ"
auto-format = true
scope = "source.templ"
injection-regex = "templ"
grammar = "templ"
file-types = ["templ"]
roots = ["go.sum"]
comment-token = "//"
indent = { tab-width = 4, unit = " " }
language-servers = [ "templ", "vscode-html-language-server" ]
formatter = { command = "templ" , args = ["fmt"] }

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = false

[[language]]
name = "go"
formatter = { command = "goimports" }
language-servers = [ "gopls" ]

[[language]]
name = "nix"
auto-format = true
language-servers = ["nil"]
[language.formatter]
command = "alejandra"

[[language]]
name = "sql"
formatter = { command = "sqlformat", args = ["--reindent", "--indent_width", "2", "--keywords", "upper", "--identifiers", "lower", "-"] }

# [[grammar]]
# name = "nix"
# source = { git = "https://github.com/nix-community/tree-sitter-nix", rev = "1b69cf1fa92366eefbe6863c184e5d2ece5f187d" }

[[language]]
name = "markdown"
file-types = ["md", "eml", "txt"]
language-servers = [ "ltex-ls"]

[[language]]
name = "html"
file-types = ["html"]
auto-format = false
language-servers = ["vscode-html-language-server"]

[[language]]
name = "css"
file-types = ["css", "scss"]
language-servers = ["vscode-css-language-server"] 

[[language]]
name = "javascript"
file-types = ["js"]
language-servers = ["typescript-language-server"]

[[language]]
name = "ruby"
scope = "source.ruby"
injection-regex = "ruby"
file-types = [
  "rb",
  "rake",
  "rakefile",
  "irb",
  "gemfile",
  "gemspec",
  "Rakefile",
  "Gemfile",
]
shebangs = ["ruby"]
comment-token = "#"
language-servers = ["solargraph", "sorbet"]
indent = { tab-width = 2, unit = "  " }
formatter = { command = "rubocop", args = ["--stdin", "foo.rb", "-a", "--stderr", "--fail-level", "fatal", "--server"] }

[language-server.sorbet]
name = "sorbet"
command = "srb"
args = ["tc", "--lsp"]

[language-server."terraform-lsp"]
command = "terraform-lsp"

[language-server.nil]
command = "nil"

[language-server."vscode-html-language-server"]
command = "vscode-html-language-server"
args = ["--add-flags", "--stdio"]

[language-server."vscode-css-language-server"]
command = "vscode-css-language-server"
args = ["--add-flags", "--stdio"] 

[language-server."typescript-language-server"]
command = "typescript-language-server"
args = ["--stdio"]

[language-server."ltex-ls"]
command = "ltex-ls"

[language-server.ltex-ls.config.ltex.dictionary]
"en-US" = ["ewwe","flaberrasted"]

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"
